name: Run Azure Login with OpenID Connect

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.5.3
      - name: Az CLI login
        uses: azure/login@v1.4.6
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      # - name: Set up Terraform
      #   uses: hashicorp/setup-terraform@v2.0.3
      #   with:
      #     terraform_version: ~1
      # - name: Terraform fmt
      #   run: terraform fmt -check
      - name: 'Run az commands'
        run: |
          az account show
          az group list
