name: Pull requests

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  tests:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.6
      - name: Cache plugin dir
        uses: actions/cache@v4.0.2
        with:
          path: ~/.tflint.d/plugins
          key: tflint-${{ hashFiles('.tflint.hcl') }}
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3.0.0
        with:
          terraform_version: ~1
      - name: Terraform fmt
        run: terraform fmt -check
      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4.0.0
        with:
          tflint_version: latest
          github_token: ${{ secrets.GITHUB_TOKEN }}
  checkov:
    name: Checkov
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4.1.6
      - name: Run Checkov
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: ./
  tfplan:
    name: Terraform Plan
    needs: checkov
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      TF_VAR_gh_pat: ${{ secrets.GH_PAT }}
      TF_VAR_resource_name_prefix: ${{ secrets.RESOURCE_NAME_PREFIX }}
      TF_VAR_vnet_cidr: ${{ secrets.VNET_CIDR }}
      TF_VAR_vault_ip_allowlist: ${{ secrets.VAULT_IP_ALLOWLIST }}
      TF_VAR_vault_admin_username: ${{ secrets.VAULT_ADMIN_USERNAME }}
      TF_VAR_dns_zone_name: ${{ secrets.DNS_ZONE_NAME }}
      TF_VAR_dns_zone_resource_group_name: ${{ secrets.DNS_ZONE_RESOURCE_GROUP_NAME }}
      TF_VAR_certbot_contact_email: ${{ secrets.CERTBOT_CONTACT_EMAIL }}
      TF_VAR_vm_timezone: ${{ vars.VM_TIMEZONE }}
      TF_VAR_vault_version: ${{ vars.VAULT_VERSION }}
      TF_VAR_key_vault_name_prefix: ${{ vars.KEY_VAULT_NAME_PREFIX }}
      TF_VAR_storage_account_name_prefix: ${{ vars.STORAGE_ACCOUNT_NAME_PREFIX }}
      TF_VAR_ssh_public_key_name: ${{ secrets.SSH_PUBLIC_KEY_NAME }}
      TF_VAR_ssh_public_key_resource_group_name: ${{ secrets.SSH_PUBLIC_KEY_RESOURCE_GROUP_NAME }}
      TF_VAR_my_aad_object_id: ${{ secrets.MY_AAD_OBJECT_ID }}
      TF_VAR_terraform_pipeline_object_id: ${{ secrets.TERRAFORM_PIPELINE_OBJECT_ID }}
      TF_VAR_acme_staging: ${{ vars.ACME_STAGING }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.6
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3.0.0
        with:
          terraform_version: ~1
      - name: Az CLI login
        uses: azure/login@v2.0.0
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
      - name: Terraform Init
        id: init
        run: terraform init
      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
